export const QuizConsts = {
    MAX_QUESTIONS: 100,
    MIN_QUESTIONS: 1,
    MAX_ANSWERS_PER_QUESTION: 10,
    MIN_ANSWERS_PER_QUESTION: 1,
    MIN_CORRECT_ANSWERS_SINGLE_CORRECT: 1,
    MIN_ANSWERS_SINGLE_CORRECT: 2,
    MIN_CORRECT_ANSWERS_MULTIPLE_CORRECT: 2,
    MIN_TOTAL_ANSWERS_MULTIPLE_CORRECT: 3,
    MIN_ANSWERS_SORTING_QUESTION: 2,
    ANSWERS_PLAIN_TEXT_QUESTION: 1,
    STRING_LENGHT_TOLERANCE: 5,
};
